"""add_market_data_columns_to_positions

Revision ID: afa7ac6615f1
Revises: 4ad1ecff0f47
Create Date: 2026-04-07 19:14:33.985997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa7ac6615f1'
down_revision: Union[str, None] = '4ad1ecff0f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('positions', sa.Column('previous_close', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('positions', sa.Column('day_change', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('positions', sa.Column('day_change_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('positions', sa.Column('position_value', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('positions', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'synced_at')
    op.drop_column('positions', 'position_value')
    op.drop_column('positions', 'day_change_pct')
    op.drop_column('positions', 'day_change')
    op.drop_column('positions', 'previous_close')
    op.drop_column('positions', 'current_price')
    # ### end Alembic commands ###
