"""add_portfolio_config_table

Revision ID: b43218f0415e
Revises: b5b08cfb7911
Create Date: 2026-04-08 01:32:16.825648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43218f0415e'
down_revision: Union[str, None] = 'b5b08cfb7911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cash_floor_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed the singleton row so the GET endpoints work without a prior PUT.
    op.execute(
        "INSERT INTO portfolio_config (id, cash_balance, cash_floor_pct) "
        "VALUES (1, 0.00, 0.10)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_config')
    # ### end Alembic commands ###
