"""add_beta_to_positions

Revision ID: e8937b49790b
Revises: afa7ac6615f1
Create Date: 2026-04-07 19:40:43.247784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8937b49790b'
down_revision: Union[str, None] = 'afa7ac6615f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'beta')
    # ### end Alembic commands ###
